feat: Implement PlDotNET support in Npgsql
- Added NpgsqlDataReader to handle data reading for PlDotNET procedural language.
- Introduced NpgsqlDataSource and NpgsqlMultiHostDataSource for managing connections.
- Created NpgsqlDataSourceBuilder for building data source instances.
- Developed NpgsqlTransaction to manage database transactions with PlDotNET.
- Implemented PoolManager to manage connection pools for PlDotNET.
- Added SPI class for importing C functions related to SPI operations.
- Created SPIHelper for handling PostgreSQL errors and managing error data.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,9 +4,9 @@ on:
   push:
     branches:
       - main
-      - 'hotfix/**'
+      - "hotfix/**"
     tags:
-      - '*'
+      - "*"
   pull_request:
 
 # Cancel previous PR branch commits (head_ref is only defined on PRs)
@@ -15,7 +15,7 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  dotnet_sdk_version: '9.0.100'
+  dotnet_sdk_version: "9.0.100"
   postgis_version: 3
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
   # Windows comes with PG pre-installed, and defines the PGPASSWORD environment variable. Remove it as it interferes
@@ -32,25 +32,25 @@ jobs:
         os: [ubuntu-22.04]
         pg_major: [17, 16, 15, 14, 13]
         config: [Release]
-        test_tfm: [net8.0]
+        test_tfm: [net9.0]
         include:
           - os: ubuntu-22.04
             pg_major: 17
             config: Debug
-            test_tfm: net8.0
+            test_tfm: net9.0
           - os: macos-15
             pg_major: 16
             config: Release
-            test_tfm: net8.0
+            test_tfm: net9.0
           - os: windows-2022
             pg_major: 17
             config: Release
-            test_tfm: net8.0
-#          - os: ubuntu-22.04
-#            pg_major: 17
-#            config: Release
-#            test_tfm: net8.0
-#            pg_prerelease: 'PG Prerelease'
+            test_tfm: net9.0
+    #          - os: ubuntu-22.04
+    #            pg_major: 17
+    #            config: Release
+    #            test_tfm: net9.0
+    #            pg_prerelease: 'PG Prerelease'
 
     outputs:
       is_release: ${{ steps.analyze_tag.outputs.is_release }}
@@ -91,14 +91,14 @@ jobs:
           sudo apt-get update -qq
           sudo apt-get install -qq postgresql-${{ matrix.pg_major }}
           export PGDATA=/etc/postgresql/${{ matrix.pg_major }}/main
-          
+
           sudo cp $GITHUB_WORKSPACE/.build/{server.crt,server.key,ca.crt} $PGDATA
           sudo chmod 600 $PGDATA/{server.crt,server.key,ca.crt}
           sudo chown postgres $PGDATA/{server.crt,server.key,ca.crt}
-          
+
           # Create npgsql_tests user with md5 password 'npgsql_tests'
           sudo -u postgres psql -c "CREATE USER npgsql_tests SUPERUSER PASSWORD 'md5adf74603a5772843f53e812f03dacb02'"
-          
+
           sudo -u postgres psql -c "CREATE USER npgsql_tests_ssl SUPERUSER PASSWORD 'npgsql_tests_ssl'"
           sudo -u postgres psql -c "CREATE USER npgsql_tests_nossl SUPERUSER PASSWORD 'npgsql_tests_nossl'"
 
@@ -106,7 +106,7 @@ jobs:
           if [ -z "${{ matrix.pg_prerelease }}" ]; then
             sudo apt-get install -qq postgresql-${{ matrix.pg_major }}-postgis-${{ env.postgis_version }}
           fi
-          
+
           if [ ${{ matrix.pg_major }} -ge 14 ]; then
             sudo sed -i "s|unix_socket_directories = '/var/run/postgresql'|unix_socket_directories = '/var/run/postgresql, @/npgsql_unix'|" $PGDATA/postgresql.conf
           fi
@@ -134,12 +134,12 @@ jobs:
           sudo sh -c "echo 'hostssl all npgsql_tests_nossl all reject' >> $PGDATA/pg_hba.conf"
           sudo sh -c "echo 'host all all all md5' >> $PGDATA/pg_hba.conf"
           sudo sh -c "echo 'host replication all all md5' >> $PGDATA/pg_hba.conf"
-          
+
           sudo pg_ctlcluster ${{ matrix.pg_major }} main restart
 
           # user 'npgsql_tests_scram' must be created with password encrypted as scram-sha-256 (which only applies after restart)
           sudo -u postgres psql -c "CREATE USER npgsql_tests_scram SUPERUSER PASSWORD 'npgsql_tests_scram'"
-          
+
       # Uncomment the following to SSH into the agent running the build (https://github.com/mxschmitt/action-tmate)
       #- uses: actions/checkout@v4
       #- name: Setup tmate session
@@ -204,7 +204,7 @@ jobs:
 
           # Create npgsql_tests user with md5 password 'npgsql_tests'
           pgsql/bin/psql -U postgres -c "CREATE ROLE npgsql_tests SUPERUSER LOGIN PASSWORD 'md5adf74603a5772843f53e812f03dacb02'"
-          
+
           pgsql/bin/psql -U postgres -c "CREATE ROLE npgsql_tests_ssl SUPERUSER LOGIN PASSWORD 'npgsql_tests_ssl'"
           pgsql/bin/psql -U postgres -c "CREATE ROLE npgsql_tests_nossl SUPERUSER LOGIN PASSWORD 'npgsql_tests_nossl'"
 
@@ -237,89 +237,89 @@ jobs:
       - name: Start PostgreSQL ${{ matrix.pg_major }} (MacOS)
         if: startsWith(matrix.os, 'macos')
         run: |
-            brew install postgresql@${{ matrix.pg_major }}
-          
-            PGDATA=/opt/homebrew/var/postgresql@${{ matrix.pg_major }}
+          brew install postgresql@${{ matrix.pg_major }}
 
-            sudo sed -i '' 's/#ssl = off/ssl = on/' $PGDATA/postgresql.conf
-            sudo sed -i '' "s/#ssl_ca_file =/ssl_ca_file = 'ca.crt' #/" $PGDATA/postgresql.conf
-            cp $GITHUB_WORKSPACE/.build/{server.crt,server.key,ca.crt} $PGDATA
-            chmod 600 $PGDATA/{server.crt,server.key,ca.crt}
-            
-            postgreService=$(brew services list | grep -oe "postgresql@${{ matrix.pg_major }}\S*")
+          PGDATA=/opt/homebrew/var/postgresql@${{ matrix.pg_major }}
 
-            brew services start $postgreService
-            export PATH="/opt/homebrew/opt/postgresql@${{ matrix.pg_major }}/bin:$PATH"
-            echo "Check PostgreSQL service is running"
-            i=5
-            COMMAND='pg_isready'
-            while [ $i -gt 0 ]; do
-                echo "Check PostgreSQL service status"
-                eval $COMMAND && break
-                ((i--))
-                if [ $i == 0 ]; then
-                    echo "PostgreSQL service not ready, all attempts exhausted"
-                    exit 1
-                fi
-                echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
-                sleep 5
-            done
-            
-            # Create npgsql_tests user with md5 password 'npgsql_tests'
-            psql -c "CREATE USER npgsql_tests SUPERUSER PASSWORD 'md5adf74603a5772843f53e812f03dacb02'" postgres
-            
-            psql -c "CREATE USER npgsql_tests_ssl SUPERUSER PASSWORD 'npgsql_tests_ssl'" postgres
-            psql -c "CREATE USER npgsql_tests_nossl SUPERUSER PASSWORD 'npgsql_tests_nossl'" postgres
+          sudo sed -i '' 's/#ssl = off/ssl = on/' $PGDATA/postgresql.conf
+          sudo sed -i '' "s/#ssl_ca_file =/ssl_ca_file = 'ca.crt' #/" $PGDATA/postgresql.conf
+          cp $GITHUB_WORKSPACE/.build/{server.crt,server.key,ca.crt} $PGDATA
+          chmod 600 $PGDATA/{server.crt,server.key,ca.crt}
 
-            sudo sed -i '' 's/max_connections = 100/max_connections = 500/' $PGDATA/postgresql.conf
-            sudo sed -i '' 's/#password_encryption = md5/password_encryption = scram-sha-256/' $PGDATA/postgresql.conf
-            sudo sed -i '' 's/#wal_level =/wal_level = logical #/' $PGDATA/postgresql.conf
-            sudo sed -i '' 's/#max_wal_senders =/max_wal_senders = 50 #/' $PGDATA/postgresql.conf
-            sudo sed -i '' 's/#logical_decoding_work_mem =/logical_decoding_work_mem = 64kB #/' $PGDATA/postgresql.conf
-            sudo sed -i '' 's/#wal_sender_timeout =/wal_sender_timeout = 3s #/' $PGDATA/postgresql.conf
-            sudo sed -i '' "s/#synchronous_standby_names =/synchronous_standby_names = 'npgsql_test_sync_standby' #/" $PGDATA/postgresql.conf
-            sudo sed -i '' "s/#synchronous_commit =/synchronous_commit = local #/" $PGDATA/postgresql.conf
-            sudo sed -i '' "s/#max_prepared_transactions = 0/max_prepared_transactions = 100/" $PGDATA/postgresql.conf
-            # Disable trust authentication, requiring MD5 passwords - some tests must fail if a password isn't provided.
-            sudo sh -c "echo 'local all all trust' > $PGDATA/pg_hba.conf"
-            sudo sh -c "echo 'hostssl all npgsql_tests_ssl all md5' >> $PGDATA/pg_hba.conf"
-            sudo sh -c "echo 'hostnossl all npgsql_tests_ssl all reject' >> $PGDATA/pg_hba.conf"
-            sudo sh -c "echo 'hostnossl all npgsql_tests_nossl all md5' >> $PGDATA/pg_hba.conf"
-            sudo sh -c "echo 'hostssl all npgsql_tests_nossl all reject' >> $PGDATA/pg_hba.conf"
-            sudo sh -c "echo 'host all npgsql_tests_scram all scram-sha-256' >> $PGDATA/pg_hba.conf"
-            sudo sh -c "echo 'host all all all md5' >> $PGDATA/pg_hba.conf"
-            sudo sh -c "echo 'host replication all all md5' >> $PGDATA/pg_hba.conf"
+          postgreService=$(brew services list | grep -oe "postgresql@${{ matrix.pg_major }}\S*")
 
-            brew services restart $postgreService
-            echo "Check PostgreSQL service is running"
-            i=5
-            COMMAND='pg_isready'
-            while [ $i -gt 0 ]; do
-                echo "Check PostgreSQL service status"
-                eval $COMMAND && break
-                ((i--))
-                if [ $i == 0 ]; then
-                    echo "PostgreSQL service not ready, all attempts exhausted"
-                    exit 1
-                fi
-                echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
-                sleep 5
-            done
-            psql -c "CREATE USER npgsql_tests_scram SUPERUSER PASSWORD 'npgsql_tests_scram'" postgres
+          brew services start $postgreService
+          export PATH="/opt/homebrew/opt/postgresql@${{ matrix.pg_major }}/bin:$PATH"
+          echo "Check PostgreSQL service is running"
+          i=5
+          COMMAND='pg_isready'
+          while [ $i -gt 0 ]; do
+              echo "Check PostgreSQL service status"
+              eval $COMMAND && break
+              ((i--))
+              if [ $i == 0 ]; then
+                  echo "PostgreSQL service not ready, all attempts exhausted"
+                  exit 1
+              fi
+              echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
+              sleep 5
+          done
+
+          # Create npgsql_tests user with md5 password 'npgsql_tests'
+          psql -c "CREATE USER npgsql_tests SUPERUSER PASSWORD 'md5adf74603a5772843f53e812f03dacb02'" postgres
+
+          psql -c "CREATE USER npgsql_tests_ssl SUPERUSER PASSWORD 'npgsql_tests_ssl'" postgres
+          psql -c "CREATE USER npgsql_tests_nossl SUPERUSER PASSWORD 'npgsql_tests_nossl'" postgres
+
+          sudo sed -i '' 's/max_connections = 100/max_connections = 500/' $PGDATA/postgresql.conf
+          sudo sed -i '' 's/#password_encryption = md5/password_encryption = scram-sha-256/' $PGDATA/postgresql.conf
+          sudo sed -i '' 's/#wal_level =/wal_level = logical #/' $PGDATA/postgresql.conf
+          sudo sed -i '' 's/#max_wal_senders =/max_wal_senders = 50 #/' $PGDATA/postgresql.conf
+          sudo sed -i '' 's/#logical_decoding_work_mem =/logical_decoding_work_mem = 64kB #/' $PGDATA/postgresql.conf
+          sudo sed -i '' 's/#wal_sender_timeout =/wal_sender_timeout = 3s #/' $PGDATA/postgresql.conf
+          sudo sed -i '' "s/#synchronous_standby_names =/synchronous_standby_names = 'npgsql_test_sync_standby' #/" $PGDATA/postgresql.conf
+          sudo sed -i '' "s/#synchronous_commit =/synchronous_commit = local #/" $PGDATA/postgresql.conf
+          sudo sed -i '' "s/#max_prepared_transactions = 0/max_prepared_transactions = 100/" $PGDATA/postgresql.conf
+          # Disable trust authentication, requiring MD5 passwords - some tests must fail if a password isn't provided.
+          sudo sh -c "echo 'local all all trust' > $PGDATA/pg_hba.conf"
+          sudo sh -c "echo 'hostssl all npgsql_tests_ssl all md5' >> $PGDATA/pg_hba.conf"
+          sudo sh -c "echo 'hostnossl all npgsql_tests_ssl all reject' >> $PGDATA/pg_hba.conf"
+          sudo sh -c "echo 'hostnossl all npgsql_tests_nossl all md5' >> $PGDATA/pg_hba.conf"
+          sudo sh -c "echo 'hostssl all npgsql_tests_nossl all reject' >> $PGDATA/pg_hba.conf"
+          sudo sh -c "echo 'host all npgsql_tests_scram all scram-sha-256' >> $PGDATA/pg_hba.conf"
+          sudo sh -c "echo 'host all all all md5' >> $PGDATA/pg_hba.conf"
+          sudo sh -c "echo 'host replication all all md5' >> $PGDATA/pg_hba.conf"
+
+          brew services restart $postgreService
+          echo "Check PostgreSQL service is running"
+          i=5
+          COMMAND='pg_isready'
+          while [ $i -gt 0 ]; do
+              echo "Check PostgreSQL service status"
+              eval $COMMAND && break
+              ((i--))
+              if [ $i == 0 ]; then
+                  echo "PostgreSQL service not ready, all attempts exhausted"
+                  exit 1
+              fi
+              echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
+              sleep 5
+          done
+          psql -c "CREATE USER npgsql_tests_scram SUPERUSER PASSWORD 'npgsql_tests_scram'" postgres
 
       # TODO: Once test/Npgsql.Specification.Tests work, switch to just testing on the solution
       - name: Test
         run: |
-            dotnet test -c ${{ matrix.config }} -f ${{ matrix.test_tfm }} test/Npgsql.Tests --logger "GitHubActions;report-warnings=false"
-            dotnet test -c ${{ matrix.config }} -f ${{ matrix.test_tfm }} test/Npgsql.DependencyInjection.Tests --logger "GitHubActions;report-warnings=false"
+          dotnet test -c ${{ matrix.config }} -f ${{ matrix.test_tfm }} test/Npgsql.Tests --logger "GitHubActions;report-warnings=false"
+          dotnet test -c ${{ matrix.config }} -f ${{ matrix.test_tfm }} test/Npgsql.DependencyInjection.Tests --logger "GitHubActions;report-warnings=false"
         shell: bash
 
       - name: Test Plugins
         if: "!startsWith(matrix.os, 'macos')"
         run: |
-            if [ -z "${{ matrix.pg_prerelease }}" ]; then
-                dotnet test -c ${{ matrix.config }} -f ${{ matrix.test_tfm }} test/Npgsql.PluginTests --logger "GitHubActions;report-warnings=false"
-            fi
+          if [ -z "${{ matrix.pg_prerelease }}" ]; then
+              dotnet test -c ${{ matrix.config }} -f ${{ matrix.test_tfm }} test/Npgsql.PluginTests --logger "GitHubActions;report-warnings=false"
+          fi
         shell: bash
 
       - id: analyze_tag
@@ -393,7 +393,7 @@ jobs:
           dotnet-version: ${{ env.dotnet_sdk_version }}
 
       - name: Pack
-        run: dotnet pack Npgsql.sln --configuration Release --property:PackageOutputPath="$PWD/nupkgs" -p:ContinuousIntegrationBuild=true      
+        run: dotnet pack Npgsql.sln --configuration Release --property:PackageOutputPath="$PWD/nupkgs" -p:ContinuousIntegrationBuild=true
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
